"""Milestone 4d: the calculator APP — 2066 engine compiled to JavaScript,
embedded in a real UI, verified under node (the browser's engine)."""

import json
import shutil
import subprocess
import unittest
from pathlib import Path

from runtime import export_javascript, parse_source
from tests.helpers import ROOT, example, run_cli

# Verifying exported JS actually executes requires node; skip cleanly when
# the runtime is deployed without a JS toolchain (servers, slim images).
HAS_NODE = shutil.which("node") is not None

APP = Path("examples/calculator_app")
ENGINE = APP / "engine.ai"
ENGINE_JS = APP / "engine.js"

CASES = [
    ("12", "3.5", "+", "15.5"),
    ("6", "7", "*", "42.0"),
    ("7", "9", "-", "-2.0"),
    ("10", "0", "/", "Cannot divide by zero"),
    ("1", "2", "%", "Unsupported operator"),
    ("12", "4", "/", "3.0"),
]


def node_eval(script: str) -> str:
    proc = subprocess.run(
        ["node", "-e", script],
        capture_output=True, text=True, timeout=60, cwd=ROOT,
    )
    if proc.returncode != 0:
        raise AssertionError(f"node failed:\n{proc.stderr}")
    return proc.stdout


class TestJavascriptExport(unittest.TestCase):
    @unittest.skipUnless(HAS_NODE, "node not available on this machine")
    def test_engine_library_loads_and_calculates_under_node(self):
        engine_js = ENGINE_JS.read_text(encoding="utf-8")
        calls = ";".join(
            f"console.log(Calc2066.calculate({a}, {b}, {json.dumps(op)}));"
            for a, b, op, _ in CASES
        )
        out = node_eval(
            f"eval(require('fs').readFileSync("
            f"{json.dumps(str(ENGINE_JS))}, 'utf8')); {calls}"
        )
        self.assertEqual(out.splitlines(), [expected for *_, expected in CASES])

    def test_exported_js_is_deterministic_and_hash_stamped(self):
        program = parse_source(ENGINE.read_text(encoding="utf-8"))
        a = export_javascript(program, library=True)
        b = export_javascript(parse_source(ENGINE.read_text(encoding="utf-8")),
                              library=True)
        self.assertEqual(a, b)
        self.assertIn("// Generated by the 2066 runtime from canonical "
                      "program sha256:", a)
        self.assertIn("globalThis.Calc2066 =", a)

    def test_library_mode_omits_main_body(self):
        generated = export_javascript(
            parse_source(ENGINE.read_text(encoding="utf-8")), library=True)
        self.assertNotIn('"*"));', generated.replace(" ", ""))  # no self-test write
        self.assertNotIn("_swrite", generated)

    @unittest.skipUnless(HAS_NODE, "node not available on this machine")
    def test_non_library_mode_runs_self_test(self):
        generated = export_javascript(
            parse_source(ENGINE.read_text(encoding="utf-8")))
        out = node_eval(generated)
        self.assertEqual(out, "42.0\n")

    def test_stdin_unsupported_in_js_target(self):
        src = 'node 001\nop system.read\noutput string\n\nnode 002\nop emit\ninput 001\n'
        with self.assertRaises(ValueError) as ctx:
            export_javascript(parse_source(src))
        self.assertIn("system.read", str(ctx.exception))

    def test_filesystem_effects_refused_like_python_target(self):
        program = parse_source(example("file_read.ai"))
        with self.assertRaises(ValueError) as ctx:
            export_javascript(program)
        self.assertIn("FILESYSTEM_READ", str(ctx.exception))

    def test_cli_javascript_target_and_library_flag(self):
        rc, _, err = run_cli("export", str(ENGINE), "--target", "javascript",
                             "--library", "--out", str(APP / "regen.js"))
        self.assertEqual((rc, err), (0, f"exported {ENGINE} -> "
                                        f"{APP / 'regen.js'} (target: javascript)\n"))
        regenerated = (APP / "regen.js").read_text(encoding="utf-8")
        self.assertEqual(regenerated, ENGINE_JS.read_text(encoding="utf-8"))
        (APP / "regen.js").unlink()

    def test_cli_rejects_unknown_target(self):
        self.assertEqual(
            run_cli("export", str(ENGINE), "--target", "wasm")[0], 3)

    def test_committed_engine_js_matches_engine_ai(self):
        """The shipped artifact must be exactly what the current engine.ai
        compiles to (no stale build artifacts)."""
        program = parse_source(ENGINE.read_text(encoding="utf-8"))
        self.assertEqual(ENGINE_JS.read_text(encoding="utf-8"),
                         export_javascript(program, library=True))


class TestEngineRuntime(unittest.TestCase):
    def test_engine_self_test_main(self):
        rc, out, err = run_cli("run", str(ENGINE))
        self.assertEqual((rc, out, err), (0, "42.0", ""))

    def test_engine_plan_adapter_identical(self):
        rc, out, _ = run_cli("run", str(ENGINE), "--adapter", "plan")
        self.assertEqual((rc, out), (0, "42.0"))

    def test_engine_effects_are_pure_plus_system(self):
        rc, out, _ = run_cli("effects", str(ENGINE), "--json")
        import json
        self.assertEqual(json.loads(out),
                         {"ok": True, "effects": ["PURE", "SYSTEM"]})


if __name__ == "__main__":
    unittest.main()
