// Generated by the 2066 runtime from canonical program sha256:c06ed086cf16db69ed502dd6b7b7892d5da3b409c7225e91026df0c364d6ae54
// Conventional source is a generated artifact — the semantic graph is the truth (roadmap §4.10). Do not edit.
function _typeof2066(v) {
  if (typeof v === "boolean") return "bool";
  if (typeof v === "number") return "f64";
  if (typeof v === "string") return "string";
  if (v === null) return "null";
  return "bytes";
}


function _fmt(v) {
  const t = _typeof2066(v);
  if (t === "bool") return v ? "true" : "false";
  if (t === "f64") return Number.isInteger(v) ? v.toFixed(1) : String(v);
  if (t === "null") return "null";
  return v;
}


function _cast(v, target) {
  const t = _typeof2066(v);
  if (t === target) return v;
  if (target === "string") return _fmt(v);
  if (target === "f64") {
    if (!/^(?:[+-]?(?:[0-9]+\.[0-9]*|\.[0-9]+)(?:[eE][+-]?[0-9]+)?|[+-]?[0-9]+[eE][+-]?[0-9]+)$/.test(v))
      throw new Error("E304 cannot cast string to f64: " + JSON.stringify(v));
    return Number(v);
  }
  if (target === "i64") {
    if (!/^[+-]?[0-9]+$/.test(v))
      throw new Error("E304 cannot cast string to i64: " + JSON.stringify(v));
    const n = Number(v);
    if (!Number.isSafeInteger(n))
      throw new Error("E304 cannot cast string to i64 (outside safe range): " + v);
    return n;
  }
  throw new Error("unreachable cast");
}


function _readline() {
  throw new Error("system.read is not available in the browser target");
}

function _f_calculate(s0, s1, s2) {
  let s3 = s0 + s1;
  let s4 = s0 - s1;
  let s5 = s0 * s1;
  let s6 = s0 / s1;
  let s7 = 0.0;
  let s8 = s1 !== s7;
  let s9 = s8 ? s6 : s7;
  let s10 = "+";
  let s11 = s2 === s10;
  let s12 = "-";
  let s13 = s2 === s12;
  let s14 = "*";
  let s15 = s2 === s14;
  let s16 = "/";
  let s17 = s2 === s16;
  let s18 = _cast(s3, "string");
  let s19 = _cast(s4, "string");
  let s20 = _cast(s5, "string");
  let s21 = _cast(s9, "string");
  let s22 = "Cannot divide by zero";
  let s23 = "Unsupported operator";
  let s24 = s8 ? s21 : s22;
  let s25 = s17 ? s24 : s23;
  let s26 = s15 ? s20 : s25;
  let s27 = s13 ? s19 : s26;
  let s28 = s11 ? s18 : s27;
  return s28;
}
globalThis.Calc2066 = { calculate: _f_calculate };
